options:
 load_pretrain: 'True'
 no_grad: 'False'
 dropout: 'default'
 spec_aug: 'False'
 spec_aug_prev: 'True'
 output_hidden_states: 'True'
 permute_input: 'False'
 ckpt_file: '/home/negiryosuke/refine/s3prl/result/pretrain/Kin2_20110524_session1_CommonAve_RegionLabel/states-200000.ckpt'
 select_layer: -1
#-------------                                    /refine/s3prl/result/pretrain/Kin2_20110524_session1_CommonAve_RegionLabel/states-200000.ckpt
args:
  mode: 'evaluate'
  evaluate_split: 'test'
  override: None
  backend: 'nccl'
  local_rank: None
  past_exp: '/home/negiryosuke/refine/s3prl/result/downstream/Kin2_20110524_session1_30s_split_CommonAve_RegionLabel/cpt200000/best-states-dev.ckpt'
  init_ckpt: '/home/negiryosuke/refine/s3prl/result/downstream/Kin2_20110524_session1_30s_split_CommonAve_RegionLabel/cpt200000/best-states-dev.ckpt'
  'config': './downstream/speaker_linear_utter_libri/config.yaml'
  'downstream': 'speaker_linear_utter_libri'
  'downstream_variant': None 
  'hub': 'torch'
  'upstream': 'tera_local'
  'upstream_ckpt': '/home/negiryosuke/refine/s3prl/result/pretrain/Kin2_20110524_session1_CommonAve_RegionLabel/states-300000.ckpt'
  'upstream_model_config': None
  'upstream_refresh': False 
  'upstream_trainable': False
  'upstream_feature_selection': 'hidden_states'
  'upstream_layer_selection': None
  'upstream_feature_normalize': False
  'upstream_model_name': 'model.pt'
  'upstream_revision': None
  'expname': 'Kin2_20110524_session1_30s_split_CommonAve_RegionLabel/cpt200000'
  'expdir': 'result/downstream/Kin2_20110524_session1_30s_split_CommonAve_RegionLabel/cpt200000'
  'auto_resume': 'False'
  'push_to_hf_hub': 'False'
  'hf_hub_org': 'None'
  'seed': 1337
  'device': 'cuda'
  'cache_dir': None 
  'verbose': False
  'disable_cudnn': False

config:
  'runner': 
    'total_steps': 1000000
    'gradient_clipping': 1
    'gradient_accumulate_steps': 1
    'log_step': 5000
    'eval_step': 10000
    'save_step': 10000
    'max_keep': 1
    'eval_dataloaders': ['dev', 'test']
  'optimizer':
    'name': 'AdamW'
    'lr': 0.0002
  'downstream_expert': 
    'datarc': 
       'num_workers': 8
       'train_batch_size': 32
       'eval_batch_size': 32
       'libri_root': '/home/negiryosuke/refine/s3prl/ECoG_data/Kin2_20110524_session1_CommonAve_ReginLabel/'
       'split_file': '/home/negiryosuke/refine/s3prl/downstream/speaker_linear_utter_libri/data/'
       'bucket_file': '/home/negiryosuke/refine/s3prl/ECoG_data/Kin2_20110524_session1_CommonAve_ReginLabel/E_data_len_for_bucket/'
       'sample_rate': 16000
       'train_dev_seed': 1337
    'modelrc': 
      'none': 'None'
init_ckpt:
  "/home/negiryosuke/refine/s3prl/result/downstream/Kin2_20110524_session1_30s_split_CommonAve_RegionLabel/cpt200000/best-states-dev.ckpt"
  
path: '/home/negiryosuke/refine/s3prl/result/pretrain/Kin2_20110524_session1_CommonAve_RegionLabel/states-200000.ckpt'


#options:{'load_pretrain': 'True', 'no_grad': 'False', 'dropout': 'default', 'spec_aug': 'False', 
# 'spec_aug_prev': 'True', 'output_hidden_states': 'True', 'permute_input': 'False', 
# 'ckpt_file': '/home/negiryosuke/refine/s3prl/result/pretrain/Kin2_20110524_session1_CommonAve_RegionLabel/states-200000.ckpt', 'select_layer': -1}
#load_weights['Config'] {'runner': {'n_epochs': -1, 'total_steps': 700000, 'gradient_clipping': 5.0, 'gradient_accumulate_steps': 4, 'log_step': 100000, 'save_step': 100000, 'max_keep': 10, 'fp16': False}, 'optimizer': {'name': 'AdamW_with_schedule', 'lr': 0.0002, 'warmup_proportion': 0.07}, 'pretrain_expert': {'datarc': {'num_workers': 8, 'train_batch_size': 8, 'max_timestep': -25, 'libri_root': '/home/negiryosuke/refine/s3prl/ECoG_data/Kin2_20110524_session1_CommonAve_ReginLabel/', 'file_path': '/home/negiryosuke/refine/s3prl/ECoG_data/Kin2_20110524_session1_CommonAve_ReginLabel/E_data_len_for_bucket/', 'sets': ['train']}}}
#load_weights['Upstream_Config'] {'transformer': {'input_dim': -1, 'hidden_size': 768, 'num_hidden_layers': 3, 'num_attention_heads': 12, 'intermediate_size': 3072, 'hidden_act': 'gelu', 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'initializer_range': 0.02, 'layer_norm_eps': 1e-12, 'share_layer': False, 'pre_layer_norm': False}, 'task': {'loss': 'L1', 'sequence_length': 1500, 'position_encoding_size': 768, 'mask_proportion': 0.15, 'mask_consecutive_min': 7, 'mask_consecutive_max': 7, 'mask_allow_overlap': True, 'mask_bucket_ratio': 1.5, 'mask_frequency': 0.2, 'noise_proportion': 0.0}, 'audio': {'target_level': -25, 'win_ms': 25, 'hop_ms': 10, 'n_freq': 201, 'n_mels': 80, 'n_mfcc': 13, 'input': {'feat_type': 'mel', 'channel': 0, 'log': True, 'delta': 0, 'cmvn': True}, 'target': {'feat_type': 'mel', 'channel': 0, 'log': True, 'delta': 0, 'cmvn': True}}}
#self_config['audio'] {'target_level': -25, 'win_ms': 25, 'hop_ms': 10, 'n_freq': 201, 'n_mels': 80, 'n_mfcc': 13, 'input': {'feat_type': 'mel', 'channel': 0, 'log': True, 'delta': 0, 'cmvn': True}, 'target': {'feat_type': 'mel', 'channel': 0, 'log': True, 'delta': 0, 'cmvn': True}}

